services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      FLASK_APP: app.py
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "5001:5000"
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0 --port=5000