services:
  - type: web
    name: vitalstock-backend
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: "False"
      - key: PORT
        value: "10000"
      - key: ALLOWED_ORIGINS
        value: "https://your-frontend-domain.vercel.app"
