"""add hardware_api_key to botiquines

Revision ID: 5ffe5abb6379
Revises: 
Create Date: 2026-05-11 22:41:14.318147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ffe5abb6379'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('botiquines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hardware_api_key', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_botiquines_hardware_api_key'), ['hardware_api_key'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('botiquines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_botiquines_hardware_api_key'))
        batch_op.drop_column('hardware_api_key')

    # ### end Alembic commands ###
